### ISSUE TITLE
Error While Compiling 

### ISSUE THREAD

**Issue by CrispyBuns** [marespiaut/ElOscuro#3]
/usr/bin/ld: /usr/local/lib/libADLMIDI.a(adlmidi.cpp.o): undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line

**Comment by marespiaut** [comment]
Hello @CrispyBuns,

You are running into this error because you haven't installed `libADLMIDI`.

For now, ElOscuro requires libADLMIDI, as I'm working on this project alone. You are very welcome to contribute to make the sound and music system more flexible.

To install `libADLMIDI` just do the following

```bash
git clone https://github.com/Wohlstand/libADLMIDI
cd libADLMIDI
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install
```

Best regards.
